<main class="h-screen">
  <section>
    <div class="text-center space-y-2">
      <p class="bg-blue-200">Crear tarea</p>
    </div>
  </section>
  <section class="container mx-auto px-4">
  <form class="bg-white rounded px-4 pt-6 pb-8 mb-4">
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="username">
        Nombre de Usuario
      </label>
      <input class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Nombre de Usuario">
    </div>
    <div  class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-title">
        Título de la Tarea
      </label>
      <input class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="task-title" type="text" placeholder="Título de la Tarea">
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-description">
        Descripción de la Tarea
      </label>
      <textarea class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="task-description" placeholder="Descripción de la Tarea"></textarea>
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-status">
        Estado de la Tarea
      </label>
      <select class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="task-status">
        <option class="text-center bg-red-400">Pendiente</option>
        <option class="text-center text-yellow-500">En ejecución</option>
        <option class="text-center text-green-500">Acabado</option>
      </select>
    </div>
   
    <p class="flex bg-blue-200 my-2">
                <a class="mx-auto" href="">
                    <button class="bg-blue-400 py-2 px-6 hover:bg-blue-300 rounded">Guardar</button>
                </a>

            </p>
  </form>
  </section>
</main>