<main class="h-screen overflow-scroll">
  <section>
    <div class="text-center space-y-2">
      <p class="bg-blue-200">Crear tarea</p>
    </div>
  </section>
  <section class="container mx-auto px-4">
  <form action="<?= $this->baseUrl . '/task/create/'  ?>" method="POST" class="bg-white rounded px-4 pt-6 pb-8 mb-4">
   
    <div  class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-title">
        Título de la Tarea
      </label>
      <input name="title" class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="task-title" type="text" placeholder="Título de la Tarea">
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="description">
        Descripción de la Tarea
      </label>
      <textarea name="description" class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="description"  placeholder="Descripción de la Tarea"></textarea>
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="username">
        Nombre de Usuario
      </label>
      <input name="username" class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Nombre de Usuario">
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-status">
        Estado de la Tarea
      </label>
      <select name="status" class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:bg-blue-200" id="task-status">
          <?php
                    foreach (StatusEnum::cases() as $case) {
                        printf('<option class="%s" value="%s">%s</option>\n',$case->color(), $case->value, $case->label());
                    }
                ?>
      </select>
    </div>
   
    <p class="flex bg-blue-200 my-2">
                <a class="mx-auto" href="">
                    <button class="bg-blue-400 py-2 px-6 hover:bg-blue-300 rounded">Guardar</button>
                </a>

            </p>
  </form>
  </section>
</main>