<?php if (empty($this->_data) || empty($this->_data['task'])) : ?>
        <div>
            <div class="">
                No hay data
            </div>
            <div>
                <a class="btn" href="<?= $this->baseUrl . '/task'  ?>">
                    Volver
                </a>
            </div>
        </div>
    <?php else : ?>
        <?php
        $task = $this->_data['task'];
        ?>
<main class="h-screen overflow-scroll">
  <section>
    <div class="text-center space-y-2">
      <p class="bg-blue-200">Editar tarea</p>
    </div>
  </section>
  <section class="container mx-auto px-4">
  <form action="<?= '?id=' . $task['id'] ?>" method="POST" class="bg-white rounded px-4 pt-6 pb-8 mb-4">
  <input id="id" type="hidden" value="<?= $task['id']?>" name="id">
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="username">
        Nombre de Usuario
      </label>
      <input class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Nombre de Usuario">
    </div>
    <div  class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-title">
        Título de la Tarea
      </label>
      <input name="title" value="<?= $task['title']?>" class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="task-title" type="text" placeholder="Título de la Tarea">
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-description">
        Descripción de la Tarea
      </label>
      <textarea name="description"  class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="task-description" placeholder="Descripción de la Tarea">
          <?= $task['description'] ?? ''; ?>
      </textarea>
    </div>
    <div class="bg-blue-200 mb-4 text-center">
      <label class="bg-blue-400 mb-4 px-2 rounded" for="task-status">
        Estado de la Tarea
      </label>
      <select name="status" class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:bg-blue-200" id="task-status">
          <?php
                    foreach (StatusEnum::cases() as $case) {
                        if ($task['status'] == $case->value) {
                            printf('<option selected="selected" value="%s">%s</option>\n', $case->value, $case->label());

                        } else {
                            printf('<option value="%s">%s</option>\n', $case->value, $case->label());
                        }
                        
                    }
                ?>
      </select>
    </div>
                    
    <div>
        <input value="<?= $task['created_at']?>" name="created_at" readonly class="text-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="" type="text" placeholder="created at">           
    </div>

    <p class="flex bg-blue-200 my-2">
                <a class="mx-auto" href="">
                    <button class="bg-blue-400 py-2 px-6 hover:bg-blue-300 rounded">Guardar</button>
                </a>

            </p>
  </form>
  </section>
</main>
<?php endif ?>