<main class="space-y-20 h-screen">
    <section>
        <div class="text-center space-y-2">
            <p class="bg-blue-200">Listemos nuestras tareas</p>
        </div>
    </section>
    <section class="container mx-auto px-8">
        <div class="text-center py-10">
            <p class="bg-blue-200 my-2">
                <a href="task/create">
                    <button class="bg-blue-400 py-2 px-4 hover:bg-blue-300 rounded">Crear</button>
                </a>
            </p>
            <p class="bg-blue-200 my-2">
                <a href="task/list">
                    <button class="bg-blue-400 py-2 px-6 hover:bg-blue-300 rounded">Listar</button>
                </a>

            </p>

        </div>
    </section>

</main>