<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
	<header class="text-center space-y-2">
		<a href="/php_todo/web/">
			<p class="text-3xl text-bold bg-blue-400">TO-DO'S</p> 
		</a>
		                  
	</header>
	
	<?php echo $this->content(); ?>

	<footer class="sticky bottom-0">
		<div class="flex flex-col items-center bg-blue-400">
			<p class="text-center bg-blue-200 mt-auto">creado por Katia & Albert</p>
		</div>
	</footer>
</body>

</html>